/**
 * RESPIRATORY & ALLERGY MEDICINES DATABASE
 * Comprehensive collection of respiratory medicines available in Bangladesh
 */

import { MedicineKnowledgeEntry } from './medicine-knowledge-base';

export const respiratoryDatabase: MedicineKnowledgeEntry[] = [
  // Beta-2 Agonists
  {
    id: "salb-002",
    generic_name: "Salbutamol",
    brand_name: "Asthalin",
    generic_name_bn: "স্যালবুটামল",
    brand_name_bn: "অ্যাস্থালিন",
    manufacturer: "Cipla Bangladesh",
    manufacturer_bn: "সিপলা বাংলাদেশ",
    strength: "4mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Beta-2 Agonist",
    therapeutic_class_bn: "বেটা-২ এগোনিস্ট",
    indication: ["Asthma", "COPD", "Bronchospasm", "Chronic bronchitis"],
    indication_bn: ["হাঁপানি", "সিওপিডি", "ব্রঙ্কোস্প্যাজম", "দীর্ঘমেয়াদী ব্রঙ্কাইটিস"],
    alternatives: ["Ventolin", "Airomir", "Sultolin", "Salbair"],
    price_range: { min: 2.0, max: 4.0 },
    prescription_required: false,
    common_dosage: "4mg 3-4 times daily",
    common_dosage_bn: "দিনে ৩-৪ বার ৪ মিগ্রা",
    side_effects: ["Tremor", "Tachycardia", "Nervousness", "Headache"],
    side_effects_bn: ["কাঁপুনি", "হার্টবিট বৃদ্ধি", "অস্থিরতা", "মাথাব্যথা"],
    contraindications: ["Hyperthyroidism", "Severe cardiac arrhythmias"],
    contraindications_bn: ["অতিরিক্ত থাইরয়েড", "গুরুতর হার্টের ছন্দ সমস্যা"],
    drug_interactions: ["Beta blockers", "Digoxin", "MAO inhibitors"],
    drug_interactions_bn: ["বেটা ব্লকার", "ডিগক্সিন", "এমএও ইনহিবিটর"],
    storage_instructions: "Store at room temperature. Protect from light and moisture.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো ও আর্দ্রতা থেকে দূরে রাখুন।",
    warnings_precautions: ["May cause paradoxical bronchospasm", "Use with caution in heart disease"],
    warnings_precautions_bn: ["বিপরীত ব্রঙ্কোস্প্যাজম হতে পারে", "হার্টের রোগে সতর্কতার সাথে ব্যবহার করুন"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Probably safe during breastfeeding",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "বুকের দুধ খাওয়ানোর সময় সম্ভবত নিরাপদ"
    },
    product_images: ["/images/medicines/asthalin-4mg.jpg"],
    keywords_bn: ["অ্যাস্থালিন", "স্যালবুটামল", "হাঁপানি", "শ্বাসকষ্ট"]
  },

  // Inhaled Corticosteroids
  {
    id: "budeso-001",
    generic_name: "Budesonide",
    brand_name: "Pulmicort",
    generic_name_bn: "বুডেসোনাইড",
    brand_name_bn: "পালমিকর্ট",
    manufacturer: "AstraZeneca Bangladesh",
    manufacturer_bn: "অ্যাস্ট্রাজেনেকা বাংলাদেশ",
    strength: "200mcg/dose",
    form: "Turbuhaler",
    form_bn: "টার্বুহেলার",
    therapeutic_class: "Inhaled Corticosteroid",
    therapeutic_class_bn: "ইনহেইল্ড কর্টিকোস্টেরয়েড",
    indication: ["Asthma prophylaxis", "COPD", "Allergic rhinitis"],
    indication_bn: ["হাঁপানি প্রতিরোধ", "সিওপিডি", "অ্যালার্জিক রাইনাইটিস"],
    alternatives: ["Budamate", "Foracort", "Symbicort"],
    price_range: { min: 450.0, max: 650.0 },
    prescription_required: true,
    common_dosage: "200mcg twice daily",
    common_dosage_bn: "দিনে দুইবার ২০০ মাইক্রোগ্রাম",
    side_effects: ["Oral thrush", "Hoarse voice", "Cough", "Headache"],
    side_effects_bn: ["মুখে ছত্রাক", "কর্কশ স্বর", "কাশি", "মাথাব্যথা"],
    contraindications: ["Hypersensitivity to budesonide", "Untreated fungal infections"],
    contraindications_bn: ["বুডেসোনাইডে অতি সংবেদনশীলতা", "চিকিৎসা না করা ছত্রাক সংক্রমণ"],
    drug_interactions: ["CYP3A4 inhibitors", "Ketoconazole", "Erythromycin"],
    drug_interactions_bn: ["সিওয়াইপি৩এ৪ ইনহিবিটর", "কিটোকোনাজোল", "এরিথ্রোমাইসিন"],
    storage_instructions: "Store below 30°C in dry place. Do not wash with water.",
    storage_instructions_bn: "৩০° সেলসিয়াসের নিচে শুকনো জায়গায় রাখুন। পানি দিয়ে ধুবেন না।",
    warnings_precautions: ["Rinse mouth after use", "Monitor growth in children", "Taper dose gradually"],
    warnings_precautions_bn: ["ব্যবহারের পর মুখ কুলকুচি করুন", "শিশুদের বৃদ্ধি পর্যবেক্ষণ করুন", "ডোজ ধীরে ধীরে কমান"],
    pregnancy_lactation: {
      pregnancy_category: "B",
      pregnancy_info: "Generally safe during pregnancy",
      lactation_info: "Minimal systemic absorption, likely safe",
      pregnancy_info_bn: "গর্ভাবস্থায় সাধারণত নিরাপদ",
      lactation_info_bn: "সিস্টেমিক শোষণ কম, সম্ভবত নিরাপদ"
    },
    product_images: ["/images/medicines/pulmicort-turbuhaler.jpg"],
    keywords_bn: ["পালমিকর্ট", "বুডেসোনাইড", "হাঁপানি প্রতিরোধ", "ইনহেলার"]
  },

  // Antihistamines
  {
    id: "lorat-001",
    generic_name: "Loratadine",
    brand_name: "Claritin",
    generic_name_bn: "লোরাটাডিন",
    brand_name_bn: "ক্ল্যারিটিন",
    manufacturer: "Schering-Plough Bangladesh",
    manufacturer_bn: "শেরিং-প্লাফ বাংলাদেশ",
    strength: "10mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Non-sedating Antihistamine",
    therapeutic_class_bn: "নন-সিডেটিং অ্যান্টিহিস্টামিন",
    indication: ["Allergic rhinitis", "Urticaria", "Hay fever", "Skin allergies"],
    indication_bn: ["অ্যালার্জিক রাইনাইটিস", "আর্টিক্যারিয়া", "হে ফিভার", "চামড়ার অ্যালার্জি"],
    alternatives: ["Loratyne", "Clarityne", "Allerta", "Lorfast"],
    price_range: { min: 3.0, max: 6.0 },
    prescription_required: false,
    common_dosage: "10mg once daily",
    common_dosage_bn: "দিনে একবার ১০ মিগ্রা",
    side_effects: ["Headache", "Fatigue", "Dry mouth", "Nausea"],
    side_effects_bn: ["মাথাব্যথা", "ক্লান্তি", "মুখ শুকনো", "বমি বমি ভাব"],
    contraindications: ["Hypersensitivity to loratadine"],
    contraindications_bn: ["লোরাটাডিনে অতি সংবেদনশীলতা"],
    drug_interactions: ["Ketoconazole", "Erythromycin", "Cimetidine"],
    drug_interactions_bn: ["কিটোকোনাজোল", "এরিথ্রোমাইসিন", "সিমেটিডিন"],
    storage_instructions: "Store at room temperature in dry place. Protect from light.",
    storage_instructions_bn: "শুকনো জায়গায় ঘরের তাপমাত্রায় রাখুন। আলো থেকে দূরে রাখুন।",
    warnings_precautions: ["Adjust dose in liver disease", "May cause drowsiness in some patients"],
    warnings_precautions_bn: ["লিভার রোগে ডোজ সমন্বয় করুন", "কিছু রোগীর ঘুমঘুম ভাব হতে পারে"],
    pregnancy_lactation: {
      pregnancy_category: "B",
      pregnancy_info: "Generally safe during pregnancy",
      lactation_info: "Passes into breast milk in small amounts",
      pregnancy_info_bn: "গর্ভাবস্থায় সাধারণত নিরাপদ",
      lactation_info_bn: "অল্প পরিমাণ বুকের দুধে যায়"
    },
    product_images: ["/images/medicines/claritin-10mg.jpg"],
    keywords_bn: ["ক্ল্যারিটিন", "লোরাটাডিন", "অ্যালার্জি", "হাঁচি"]
  },

  // Decongestants
  {
    id: "pseudo-001",
    generic_name: "Pseudoephedrine",
    brand_name: "Sudafed",
    generic_name_bn: "সিউডোইফেড্রিন",
    brand_name_bn: "সুডাফেড",
    manufacturer: "Johnson & Johnson Bangladesh",
    manufacturer_bn: "জনসন এন্ড জনসন বাংলাদেশ",
    strength: "60mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Nasal Decongestant",
    therapeutic_class_bn: "নাক বন্ধভাব দূরকারী",
    indication: ["Nasal congestion", "Sinusitis", "Common cold", "Allergic rhinitis"],
    indication_bn: ["নাক বন্ধ", "সাইনাসাইটিস", "সাধারণ সর্দি", "অ্যালার্জিক রাইনাইটিস"],
    alternatives: ["Deconex", "Rinex", "Nasofed", "Phenylphed"],
    price_range: { min: 3.5, max: 7.0 },
    prescription_required: true,
    common_dosage: "60mg every 4-6 hours, maximum 240mg daily",
    common_dosage_bn: "৪-৬ ঘণ্টা অন্তর ৬০ মিগ্রা, সর্বোচ্চ দিনে ২৪০ মিগ্রা",
    side_effects: ["Insomnia", "Nervousness", "Dizziness", "Increased blood pressure"],
    side_effects_bn: ["অনিদ্রা", "অস্থিরতা", "মাথা ঘোরা", "রক্তচাপ বৃদ্ধি"],
    contraindications: ["Severe hypertension", "Severe coronary artery disease", "MAO inhibitor use"],
    contraindications_bn: ["গুরুতর উচ্চ রক্তচাপ", "গুরুতর করোনারী আর্টারী ডিজিজ", "এমএও ইনহিবিটর ব্যবহার"],
    drug_interactions: ["MAO inhibitors", "Beta blockers", "Methyldopa"],
    drug_interactions_bn: ["এমএও ইনহিবিটর", "বেটা ব্লকার", "মিথাইলডোপা"],
    storage_instructions: "Store at room temperature. Keep away from moisture and heat.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আর্দ্রতা ও গরম থেকে দূরে রাখুন।",
    warnings_precautions: ["Monitor blood pressure", "Use for maximum 7 days", "Avoid late evening doses"],
    warnings_precautions_bn: ["রক্তচাপ পর্যবেক্ষণ করুন", "সর্বোচ্চ ৭ দিন ব্যবহার করুন", "রাতে দেরিতে নেওয়া এড়িয়ে চলুন"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Passes into breast milk, use with caution",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "বুকের দুধে যায়, সতর্কতার সাথে ব্যবহার করুন"
    },
    product_images: ["/images/medicines/sudafed-60mg.jpg"],
    keywords_bn: ["সুডাফেড", "সিউডোইফেড্রিন", "নাক বন্ধ", "সাইনাস"]
  },

  // Cough Suppressants
  {
    id: "dextro-001",
    generic_name: "Dextromethorphan",
    brand_name: "Robitussin",
    generic_name_bn: "ডেক্সট্রোমিথরফান",
    brand_name_bn: "রবিটুসিন",
    manufacturer: "Pfizer Bangladesh",
    manufacturer_bn: "ফাইজার বাংলাদেশ",
    strength: "15mg/5ml",
    form: "Syrup",
    form_bn: "সিরাপ",
    therapeutic_class: "Antitussive",
    therapeutic_class_bn: "কাশি নিবারক",
    indication: ["Dry cough", "Non-productive cough", "Upper respiratory infections"],
    indication_bn: ["শুকনো কাশি", "অনুৎপাদনশীল কাশি", "উর্ধ্ব শ্বাসযন্ত্রের সংক্রমণ"],
    alternatives: ["Delsym", "Tussin", "Coughex", "Bronchostop"],
    price_range: { min: 45.0, max: 85.0 },
    prescription_required: false,
    common_dosage: "15ml every 4 hours, maximum 90ml daily",
    common_dosage_bn: "৪ ঘণ্টা অন্তর ১৫ মিলি, সর্বোচ্চ দিনে ৯০ মিলি",
    side_effects: ["Drowsiness", "Dizziness", "Nausea", "Constipation"],
    side_effects_bn: ["ঘুমঘুম ভাব", "মাথা ঘোরা", "বমি বমি ভাব", "কব্জি"],
    contraindications: ["MAO inhibitor use", "Chronic cough with excessive secretions"],
    contraindications_bn: ["এমএও ইনহিবিটর ব্যবহার", "অতিরিক্ত কফসহ দীর্ঘমেয়াদী কাশি"],
    drug_interactions: ["MAO inhibitors", "SSRIs", "Quinidine"],
    drug_interactions_bn: ["এমএও ইনহিবিটর", "এসএসআরআই", "কুইনিডিন"],
    storage_instructions: "Store at room temperature. Do not refrigerate. Shake well before use.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। ফ্রিজে রাখবেন না। ব্যবহারের আগে ভাল করে ঝাঁকান।",
    warnings_precautions: ["Do not exceed recommended dose", "Avoid alcohol", "May cause drowsiness"],
    warnings_precautions_bn: ["নির্ধারিত মাত্রার বেশি নেবেন না", "মদ্যপান এড়িয়ে চলুন", "ঘুমঘুম ভাব হতে পারে"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if clearly needed",
      lactation_info: "Unknown if passes into breast milk",
      pregnancy_info_bn: "স্পষ্ট প্রয়োজন থাকলেই ব্যবহার করুন",
      lactation_info_bn: "বুকের দুধে যায় কিনা জানা নেই"
    },
    product_images: ["/images/medicines/robitussin-syrup.jpg"],
    keywords_bn: ["রবিটুসিন", "ডেক্সট্রোমিথরফান", "কাশির সিরাপ", "শুকনো কাশি"]
  },

  // Expectorants
  {
    id: "guaif-001",
    generic_name: "Guaifenesin",
    brand_name: "Mucinex",
    generic_name_bn: "গুয়াইফেনেসিন",
    brand_name_bn: "মুসিনেক্স",
    manufacturer: "Reckitt Benckiser Bangladesh",
    manufacturer_bn: "রেকিট বেঙ্কিজার বাংলাদেশ",
    strength: "400mg",
    form: "Extended Release Tablet",
    form_bn: "বর্ধিত মুক্তির ট্যাবলেট",
    therapeutic_class: "Expectorant",
    therapeutic_class_bn: "কফ নিঃসারক",
    indication: ["Productive cough", "Chest congestion", "Bronchitis", "COPD"],
    indication_bn: ["কফযুক্ত কাশি", "বুকে কফ জমা", "ব্রঙ্কাইটিস", "সিওপিডি"],
    alternatives: ["Robitussin", "Expectorant", "Bronchex", "Mucosol"],
    price_range: { min: 8.0, max: 15.0 },
    prescription_required: false,
    common_dosage: "400mg every 12 hours",
    common_dosage_bn: "১২ ঘণ্টা অন্তর ৪০০ মিগ্রা",
    side_effects: ["Nausea", "Vomiting", "Stomach upset", "Dizziness"],
    side_effects_bn: ["বমি বমি ভাব", "বমি", "পেট খারাপ", "মাথা ঘোরা"],
    contraindications: ["Hypersensitivity to guaifenesin"],
    contraindications_bn: ["গুয়াইফেনেসিনে অতি সংবেদনশীলতা"],
    drug_interactions: ["No significant interactions"],
    drug_interactions_bn: ["কোনো গুরুত্বপূর্ণ ইন্টারঅ্যাকশন নেই"],
    storage_instructions: "Store at room temperature. Do not crush or chew extended-release tablets.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। বর্ধিত মুক্তির ট্যাবলেট ভাঙ্গবেন না বা চিবাবেন না।",
    warnings_precautions: ["Take with plenty of water", "Do not crush tablets", "Consult doctor for persistent cough"],
    warnings_precautions_bn: ["প্রচুর পানি দিয়ে নিন", "ট্যাবলেট ভাঙ্গবেন না", "দীর্ঘস্থায়ী কাশির জন্য ডাক্তারের পরামর্শ নিন"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Unknown if passes into breast milk",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "বুকের দুধে যায় কিনা জানা নেই"
    },
    product_images: ["/images/medicines/mucinex-400mg.jpg"],
    keywords_bn: ["মুসিনেক্স", "গুয়াইফেনেসিন", "কফ নিঃসারক", "বুকে কফ"]
  }
];

export default respiratoryDatabase;