/**
 * NEUROLOGICAL & PSYCHIATRIC MEDICINES DATABASE
 * Comprehensive collection of neurological and psychiatric medicines available in Bangladesh
 */

import { MedicineKnowledgeEntry } from './medicine-knowledge-base';

export const neurologicalDatabase: MedicineKnowledgeEntry[] = [
  // Anticonvulsants
  {
    id: "phen-001",
    generic_name: "Phenytoin",
    brand_name: "Eptoin",
    generic_name_bn: "ফেনাইটয়িন",
    brand_name_bn: "এপটয়িন",
    manufacturer: "Abbott Bangladesh",
    manufacturer_bn: "অ্যাবট বাংলাদেশ",
    strength: "100mg",
    form: "Capsule",
    form_bn: "ক্যাপসুল",
    therapeutic_class: "Anticonvulsant",
    therapeutic_class_bn: "খিঁচুনি নিবারক",
    indication: ["Epilepsy", "Seizure disorders", "Status epilepticus", "Trigeminal neuralgia"],
    indication_bn: ["মৃগীরোগ", "খিঁচুনি রোগ", "স্ট্যাটাস এপিলেপটিকাস", "ট্রাইজেমাইনাল নিউরালজিয়া"],
    alternatives: ["Dilantin", "Phenytoin Sodium", "Epanutin"],
    price_range: { min: 4.5, max: 8.0 },
    prescription_required: true,
    common_dosage: "100mg 3 times daily",
    common_dosage_bn: "দিনে ৩ বার ১০০ মিগ্রা",
    side_effects: ["Gingival hyperplasia", "Dizziness", "Drowsiness", "Nausea", "Skin rash"],
    side_effects_bn: ["মাড়ি ফোলা", "মাথা ঘোরা", "ঘুমঘুম ভাব", "বমি বমি ভাব", "চামড়ায় র‍্যাশ"],
    contraindications: ["Hypersensitivity", "Sinus bradycardia", "Heart block"],
    contraindications_bn: ["অতি সংবেদনশীলতা", "সাইনাস ব্র্যাডিকার্ডিয়া", "হার্ট ব্লক"],
    drug_interactions: ["Warfarin", "Carbamazepine", "Alcohol", "Oral contraceptives"],
    drug_interactions_bn: ["ওয়ারফারিন", "কার্বামাজেপিন", "অ্যালকোহল", "জন্মনিয়ন্ত্রণ বড়ি"],
    storage_instructions: "Store at room temperature. Protect from light and moisture.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো ও আর্দ্রতা থেকে দূরে রাখুন।",
    warnings_precautions: ["Monitor blood levels regularly", "May cause birth defects", "Gradual discontinuation required"],
    warnings_precautions_bn: ["নিয়মিত রক্তে মাত্রা পরীক্ষা করুন", "জন্মগত ত্রুটি হতে পারে", "ধীরে ধীরে বন্ধ করা প্রয়োজন"],
    pregnancy_lactation: {
      pregnancy_category: "D",
      pregnancy_info: "May cause birth defects, use only if benefits outweigh risks",
      lactation_info: "Passes into breast milk, monitor infant",
      pregnancy_info_bn: "জন্মগত ত্রুটি হতে পারে, উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "বুকের দুধে যায়, শিশুকে পর্যবেক্ষণ করুন"
    },
    product_images: ["/images/medicines/eptoin-100mg.jpg"],
    keywords_bn: ["এপটয়িন", "ফেনাইটয়িন", "মৃগীরোগ", "খিঁচুনি"]
  },

  {
    id: "carb-001",
    generic_name: "Carbamazepine",
    brand_name: "Tegretol",
    generic_name_bn: "কার্বামাজেপিন",
    brand_name_bn: "টেগ্রেটল",
    manufacturer: "Novartis Bangladesh",
    manufacturer_bn: "নোভার্টিস বাংলাদেশ",
    strength: "200mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Anticonvulsant",
    therapeutic_class_bn: "খিঁচুনি নিবারক",
    indication: ["Epilepsy", "Trigeminal neuralgia", "Bipolar disorder", "Diabetic neuropathy"],
    indication_bn: ["মৃগীরোগ", "ট্রাইজেমাইনাল নিউরালজিয়া", "বাইপোলার ডিসঅর্ডার", "ডায়াবেটিক নিউরোপ্যাথি"],
    alternatives: ["Carbatol", "Mazetol", "Carbapin"],
    price_range: { min: 5.0, max: 10.0 },
    prescription_required: true,
    common_dosage: "200mg twice daily, gradually increase",
    common_dosage_bn: "দিনে দুইবার ২০০ মিগ্রা, ধীরে ধীরে বৃদ্ধি",
    side_effects: ["Dizziness", "Drowsiness", "Nausea", "Blurred vision", "Skin reactions"],
    side_effects_bn: ["মাথা ঘোরা", "ঘুমঘুম ভাব", "বমি বমি ভাব", "ঝাপসা দৃষ্টি", "চামড়ার প্রতিক্রিয়া"],
    contraindications: ["Hypersensitivity", "Bone marrow depression", "AV heart block"],
    contraindications_bn: ["অতি সংবেদনশীলতা", "অস্থি মজ্জা দমন", "এভি হার্ট ব্লক"],
    drug_interactions: ["Phenytoin", "Lithium", "Oral contraceptives", "Warfarin"],
    drug_interactions_bn: ["ফেনাইটয়িন", "লিথিয়াম", "জন্মনিয়ন্ত্রণ বড়ি", "ওয়ারফারিন"],
    storage_instructions: "Store at room temperature in dry place. Protect from light.",
    storage_instructions_bn: "শুকনো জায়গায় ঘরের তাপমাত্রায় রাখুন। আলো থেকে দূরে রাখুন।",
    warnings_precautions: ["Monitor blood counts", "May cause Stevens-Johnson syndrome", "Avoid abrupt discontinuation"],
    warnings_precautions_bn: ["রক্তের কোষ পরীক্ষা করুন", "স্টিভেন্স-জনসন সিনড্রোম হতে পারে", "হঠাৎ বন্ধ করবেন না"],
    pregnancy_lactation: {
      pregnancy_category: "D",
      pregnancy_info: "May cause neural tube defects",
      lactation_info: "Passes into breast milk",
      pregnancy_info_bn: "নিউরাল টিউব ডিফেক্ট হতে পারে",
      lactation_info_bn: "বুকের দুধে যায়"
    },
    product_images: ["/images/medicines/tegretol-200mg.jpg"],
    keywords_bn: ["টেগ্রেটল", "কার্বামাজেপিন", "মৃগীরোগ", "নার্ভের ব্যথা"]
  },

  // Antidepressants
  {
    id: "amit-001",
    generic_name: "Amitriptyline",
    brand_name: "Tryptomer",
    generic_name_bn: "অ্যামিট্রিপটাইলিন",
    brand_name_bn: "ট্রিপটোমার",
    manufacturer: "Sun Pharma Bangladesh",
    manufacturer_bn: "সান ফার্মা বাংলাদেশ",
    strength: "25mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Tricyclic Antidepressant",
    therapeutic_class_bn: "ট্রাইসাইক্লিক অ্যান্টিডিপ্রেসান্ট",
    indication: ["Depression", "Neuropathic pain", "Migraine prophylaxis", "Insomnia"],
    indication_bn: ["বিষণ্ণতা", "নার্ভের ব্যথা", "মাইগ্রেন প্রতিরোধ", "অনিদ্রা"],
    alternatives: ["Amitone", "Tryptizol", "Amitrol"],
    price_range: { min: 3.0, max: 6.0 },
    prescription_required: true,
    common_dosage: "25mg at bedtime, gradually increase",
    common_dosage_bn: "রাতে ঘুমানোর সময় ২৫ মিগ্রা, ধীরে ধীরে বৃদ্ধি",
    side_effects: ["Drowsiness", "Dry mouth", "Constipation", "Weight gain", "Blurred vision"],
    side_effects_bn: ["ঘুমঘুম ভাব", "মুখ শুকনো", "কব্জি", "ওজন বৃদ্ধি", "ঝাপসা দৃষ্টি"],
    contraindications: ["Recent MI", "Hypersensitivity", "Narrow angle glaucoma"],
    contraindications_bn: ["সাম্প্রতিক হার্ট অ্যাটাক", "অতি সংবেদনশীলতা", "সংকীর্ণ কোণ গ্লকোমা"],
    drug_interactions: ["MAO inhibitors", "Alcohol", "Anticholinergics", "CNS depressants"],
    drug_interactions_bn: ["এমএও ইনহিবিটর", "অ্যালকোহল", "অ্যান্টিকোলিনার্জিক", "সিএনএস ডিপ্রেসান্ট"],
    storage_instructions: "Store at room temperature. Protect from light and moisture.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো ও আর্দ্রতা থেকে দূরে রাখুন।",
    warnings_precautions: ["Suicidal thoughts in young adults", "Gradual withdrawal", "Monitor for cardiac effects"],
    warnings_precautions_bn: ["তরুণদের আত্মহত্যার চিন্তা", "ধীরে ধীরে কমানো", "হৃদযন্ত্রের প্রভাব পর্যবেক্ষণ"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Passes into breast milk",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "বুকের দুধে যায়"
    },
    product_images: ["/images/medicines/tryptomer-25mg.jpg"],
    keywords_bn: ["ট্রিপটোমার", "অ্যামিট্রিপটাইলিন", "বিষণ্ণতা", "নার্ভের ব্যথা"]
  },

  {
    id: "fluox-001",
    generic_name: "Fluoxetine",
    brand_name: "Prozac",
    generic_name_bn: "ফ্লুঅক্সেটিন",
    brand_name_bn: "প্রোজাক",
    manufacturer: "Eli Lilly Bangladesh",
    manufacturer_bn: "এলি লিলি বাংলাদেশ",
    strength: "20mg",
    form: "Capsule",
    form_bn: "ক্যাপসুল",
    therapeutic_class: "SSRI Antidepressant",
    therapeutic_class_bn: "এসএসআরআই অ্যান্টিডিপ্রেসান্ট",
    indication: ["Depression", "Anxiety disorders", "OCD", "Bulimia nervosa", "PMDD"],
    indication_bn: ["বিষণ্ণতা", "উদ্বেগ রোগ", "ওসিডি", "বুলিমিয়া নার্ভোসা", "পিএমডিডি"],
    alternatives: ["Fludep", "Flunil", "Oxetine"],
    price_range: { min: 6.0, max: 12.0 },
    prescription_required: true,
    common_dosage: "20mg once daily in morning",
    common_dosage_bn: "সকালে একবার ২০ মিগ্রা",
    side_effects: ["Nausea", "Insomnia", "Sexual dysfunction", "Headache", "Nervousness"],
    side_effects_bn: ["বমি বমি ভাব", "অনিদ্রা", "যৌন সমস্যা", "মাথাব্যথা", "অস্থিরতা"],
    contraindications: ["MAO inhibitor use", "Hypersensitivity", "Concurrent thioridazine"],
    contraindications_bn: ["এমএও ইনহিবিটর ব্যবহার", "অতি সংবেদনশীলতা", "থায়োরিডাজিনের সাথে"],
    drug_interactions: ["MAO inhibitors", "Warfarin", "Phenytoin", "Lithium"],
    drug_interactions_bn: ["এমএও ইনহিবিটর", "ওয়ারফারিন", "ফেনাইটয়িন", "লিথিয়াম"],
    storage_instructions: "Store at room temperature. Protect from moisture.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আর্দ্রতা থেকে দূরে রাখুন।",
    warnings_precautions: ["Suicidal thoughts", "Serotonin syndrome", "Gradual discontinuation"],
    warnings_precautions_bn: ["আত্মহত্যার চিন্তা", "সেরোটোনিন সিনড্রোম", "ধীরে ধীরে কমানো"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use during pregnancy only if clearly needed",
      lactation_info: "Passes into breast milk",
      pregnancy_info_bn: "গর্ভাবস্থায় স্পষ্ট প্রয়োজন থাকলেই ব্যবহার করুন",
      lactation_info_bn: "বুকের দুধে যায়"
    },
    product_images: ["/images/medicines/prozac-20mg.jpg"],
    keywords_bn: ["প্রোজাক", "ফ্লুঅক্সেটিন", "বিষণ্ণতা", "উদ্বেগ"]
  },

  // Anxiolytics
  {
    id: "alpra-001",
    generic_name: "Alprazolam",
    brand_name: "Xanax",
    generic_name_bn: "আল্প্রাজোলাম",
    brand_name_bn: "জ্যানাক্স",
    manufacturer: "Pfizer Bangladesh",
    manufacturer_bn: "ফাইজার বাংলাদেশ",
    strength: "0.5mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Benzodiazepine Anxiolytic",
    therapeutic_class_bn: "বেনজোডায়াজেপিন উদ্বেগনাশক",
    indication: ["Anxiety disorders", "Panic disorder", "Insomnia", "Phobias"],
    indication_bn: ["উদ্বেগ রোগ", "প্যানিক ডিসঅর্ডার", "অনিদ্রা", "ভীতি"],
    alternatives: ["Alprazolam", "Zolam", "Alzam"],
    price_range: { min: 2.0, max: 5.0 },
    prescription_required: true,
    common_dosage: "0.25-0.5mg 2-3 times daily",
    common_dosage_bn: "দিনে ২-৩ বার ০.২৫-০.৫ মিগ্রা",
    side_effects: ["Drowsiness", "Dizziness", "Memory impairment", "Confusion", "Weakness"],
    side_effects_bn: ["ঘুমঘুম ভাব", "মাথা ঘোরা", "স্মৃতিশক্তি কমে যাওয়া", "বিভ্রান্তি", "দুর্বলতা"],
    contraindications: ["Hypersensitivity", "Narrow angle glaucoma", "Severe respiratory depression"],
    contraindications_bn: ["অতি সংবেদনশীলতা", "সংকীর্ণ কোণ গ্লকোমা", "গুরুতর শ্বাসকষ্ট"],
    drug_interactions: ["Alcohol", "CNS depressants", "Ketoconazole", "Cimetidine"],
    drug_interactions_bn: ["অ্যালকোহল", "সিএনএস ডিপ্রেসান্ট", "কিটোকোনাজোল", "সিমেটিডিন"],
    storage_instructions: "Store at room temperature. Keep in original container.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। মূল কন্টেইনারে রাখুন।",
    warnings_precautions: ["Habit forming", "Avoid abrupt discontinuation", "May impair driving"],
    warnings_precautions_bn: ["অভ্যাস গঠন করে", "হঠাৎ বন্ধ করবেন না", "গাড়ি চালানোতে সমস্যা হতে পারে"],
    pregnancy_lactation: {
      pregnancy_category: "D",
      pregnancy_info: "May cause birth defects",
      lactation_info: "Passes into breast milk",
      pregnancy_info_bn: "জন্মগত ত্রুটি হতে পারে",
      lactation_info_bn: "বুকের দুধে যায়"
    },
    product_images: ["/images/medicines/xanax-0.5mg.jpg"],
    keywords_bn: ["জ্যানাক্স", "আল্প্রাজোলাম", "উদ্বেগ", "প্যানিক"]
  },

  // Antipsychotics
  {
    id: "halo-001",
    generic_name: "Haloperidol",
    brand_name: "Haldol",
    generic_name_bn: "হালোপেরিডল",
    brand_name_bn: "হালডল",
    manufacturer: "Janssen Bangladesh",
    manufacturer_bn: "জ্যানসেন বাংলাদেশ",
    strength: "5mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Typical Antipsychotic",
    therapeutic_class_bn: "সাধারণ অ্যান্টিসাইকোটিক",
    indication: ["Schizophrenia", "Acute psychosis", "Bipolar mania", "Tourette syndrome"],
    indication_bn: ["সিজোফ্রেনিয়া", "তীব্র মানসিক বিকার", "বাইপোলার ম্যানিয়া", "টুরেট সিনড্রোম"],
    alternatives: ["Serenace", "Halojoy", "Halozen"],
    price_range: { min: 4.0, max: 8.0 },
    prescription_required: true,
    common_dosage: "5-10mg twice daily",
    common_dosage_bn: "দিনে দুইবার ৫-১০ মিগ্রা",
    side_effects: ["Extrapyramidal symptoms", "Sedation", "Dry mouth", "Constipation", "Weight gain"],
    side_effects_bn: ["এক্সট্রাপিরামিডাল উপসর্গ", "তন্দ্রা", "মুখ শুকনো", "কব্জি", "ওজন বৃদ্ধি"],
    contraindications: ["Hypersensitivity", "Severe CNS depression", "Parkinson's disease"],
    contraindications_bn: ["অতি সংবেদনশীলতা", "গুরুতর সিএনএস দমন", "পারকিনসন রোগ"],
    drug_interactions: ["Alcohol", "CNS depressants", "Anticholinergics", "Lithium"],
    drug_interactions_bn: ["অ্যালকোহল", "সিএনএস ডিপ্রেসান্ট", "অ্যান্টিকোলিনার্জিক", "লিথিয়াম"],
    storage_instructions: "Store at room temperature. Protect from light.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো থেকে দূরে রাখুন।",
    warnings_precautions: ["Monitor for tardive dyskinesia", "Risk of neuroleptic malignant syndrome", "Regular ECG monitoring"],
    warnings_precautions_bn: ["টারডিভ ডিসকাইনেসিয়া পর্যবেক্ষণ", "নিউরোলেপটিক ম্যালিগন্যান্ট সিনড্রোমের ঝুঁকি", "নিয়মিত ইসিজি পরীক্ষা"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Passes into breast milk",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "বুকের দুধে যায়"
    },
    product_images: ["/images/medicines/haldol-5mg.jpg"],
    keywords_bn: ["হালডল", "হালোপেরিডল", "সিজোফ্রেনিয়া", "মানসিক রোগ"]
  },

  // Mood Stabilizers
  {
    id: "lith-001",
    generic_name: "Lithium Carbonate",
    brand_name: "Lithobid",
    generic_name_bn: "লিথিয়াম কার্বোনেট",
    brand_name_bn: "লিথোবিড",
    manufacturer: "Nuvista Pharma",
    manufacturer_bn: "নুভিস্তা ফার্মা",
    strength: "300mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Mood Stabilizer",
    therapeutic_class_bn: "মুড স্ট্যাবিলাইজার",
    indication: ["Bipolar disorder", "Mania", "Depression (adjunct)", "Recurrent depression"],
    indication_bn: ["বাইপোলার ডিসঅর্ডার", "ম্যানিয়া", "বিষণ্ণতা (সহায়ক)", "পুনরাবৃত্ত বিষণ্ণতা"],
    alternatives: ["Lithium", "Lithocarb", "Camcolit"],
    price_range: { min: 5.0, max: 10.0 },
    prescription_required: true,
    common_dosage: "300mg 2-3 times daily",
    common_dosage_bn: "দিনে ২-৩ বার ৩০০ মিগ্রা",
    side_effects: ["Tremor", "Increased urination", "Thirst", "Weight gain", "Nausea"],
    side_effects_bn: ["কাঁপুনি", "প্রস্রাব বৃদ্ধি", "তৃষ্ণা", "ওজন বৃদ্ধি", "বমি বমি ভাব"],
    contraindications: ["Renal impairment", "Cardiovascular disease", "Dehydration"],
    contraindications_bn: ["কিডনি সমস্যা", "হৃদরোগ", "পানিশূন্যতা"],
    drug_interactions: ["Diuretics", "NSAIDs", "ACE inhibitors", "Carbamazepine"],
    drug_interactions_bn: ["মূত্রবর্ধক", "এনএসএআইডি", "এসিই ইনহিবিটর", "কার্বামাজেপিন"],
    storage_instructions: "Store at room temperature in dry place. Keep tightly closed.",
    storage_instructions_bn: "শুকনো জায়গায় ঘরের তাপমাত্রায় রাখুন। শক্ত করে বন্ধ রাখুন।",
    warnings_precautions: ["Monitor serum lithium levels", "Maintain adequate fluid intake", "Regular kidney function tests"],
    warnings_precautions_bn: ["সিরাম লিথিয়াম লেভেল পরীক্ষা করুন", "পর্যাপ্ত পানি পান করুন", "নিয়মিত কিডনি পরীক্ষা"],
    pregnancy_lactation: {
      pregnancy_category: "D",
      pregnancy_info: "May cause cardiac defects in fetus",
      lactation_info: "Passes into breast milk, contraindicated",
      pregnancy_info_bn: "ভ্রূণের হার্টের সমস্যা হতে পারে",
      lactation_info_bn: "বুকের দুধে যায়, নিষিদ্ধ"
    },
    product_images: ["/images/medicines/lithobid-300mg.jpg"],
    keywords_bn: ["লিথোবিড", "লিথিয়াম", "বাইপোলার", "ম্যানিয়া"]
  }
];

export default neurologicalDatabase;