/**
 * OPHTHALMOLOGICAL MEDICINES DATABASE
 * Comprehensive collection of eye medicines available in Bangladesh
 */

import { MedicineKnowledgeEntry } from './medicine-knowledge-base';

export const ophthalmologicalDatabase: MedicineKnowledgeEntry[] = [
  // Antibiotic Eye Drops
  {
    id: "chlor-eye-001",
    generic_name: "Chloramphenicol",
    brand_name: "Chloromycetin",
    generic_name_bn: "ক্লোরামফেনিকল",
    brand_name_bn: "ক্লোরোমাইসেটিন",
    manufacturer: "Pfizer Bangladesh",
    manufacturer_bn: "ফাইজার বাংলাদেশ",
    strength: "0.5%",
    form: "Eye Drops",
    form_bn: "চোখের ড্রপ",
    therapeutic_class: "Ophthalmic Antibiotic",
    therapeutic_class_bn: "চোখের এন্টিবায়োটিক",
    indication: ["Bacterial conjunctivitis", "Corneal ulcer", "Blepharitis", "Eye infections"],
    indication_bn: ["ব্যাকটেরিয়াল কনজাংটিভাইটিস", "কর্নিয়াল আলসার", "ব্লেফারাইটিস", "চোখের সংক্রমণ"],
    alternatives: ["Chloramphenicol", "Spersanicol", "Kemicetine"],
    price_range: { min: 15.0, max: 30.0 },
    prescription_required: true,
    common_dosage: "1-2 drops 4-6 times daily",
    common_dosage_bn: "দিনে ৪-৬ বার ১-২ ড্রপ",
    side_effects: ["Local irritation", "Burning sensation", "Temporary blurred vision", "Allergic reactions"],
    side_effects_bn: ["স্থানীয় জ্বালা", "জ্বালাপোড়া", "সাময়িক ঝাপসা দৃষ্টি", "অ্যালার্জিক প্রতিক্রিয়া"],
    contraindications: ["Hypersensitivity to chloramphenicol", "Viral eye infections", "Fungal eye infections"],
    contraindications_bn: ["ক্লোরামফেনিকল অতি সংবেদনশীলতা", "ভাইরাল চোখের সংক্রমণ", "ছত্রাক চোখের সংক্রমণ"],
    drug_interactions: ["Other topical antibiotics"],
    drug_interactions_bn: ["অন্যান্য বাহ্যিক এন্টিবায়োটিক"],
    storage_instructions: "Store at 2-8°C. Do not freeze. Use within 28 days of opening.",
    storage_instructions_bn: "২-৮° সেলসিয়াসে রাখুন। হিমায়িত করবেন না। খোলার ২৮ দিনের মধ্যে ব্যবহার করুন।",
    warnings_precautions: ["For ophthalmic use only", "Remove contact lenses before use", "Do not touch dropper to eye"],
    warnings_precautions_bn: ["শুধুমাত্র চোখের জন্য", "ব্যবহারের আগে কন্ট্যাক্ট লেন্স খুলে নিন", "ড্রপারে চোখ লাগাবেন না"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Use with caution",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "সতর্কতার সাথে ব্যবহার করুন"
    },
    product_images: ["/images/medicines/chloromycetin-eye-drops.jpg"],
    keywords_bn: ["ক্লোরোমাইসেটিন", "ক্লোরামফেনিকল", "চোখের ইনফেকশন", "কনজাংটিভাইটিস"]
  },

  {
    id: "tobra-001",
    generic_name: "Tobramycin",
    brand_name: "Tobrex",
    generic_name_bn: "টব্রামাইসিন",
    brand_name_bn: "টব্রেক্স",
    manufacturer: "Alcon Bangladesh",
    manufacturer_bn: "অ্যালকন বাংলাদেশ",
    strength: "0.3%",
    form: "Eye Drops",
    form_bn: "চোখের ড্রপ",
    therapeutic_class: "Ophthalmic Antibiotic",
    therapeutic_class_bn: "চোখের এন্টিবায়োটিক",
    indication: ["Bacterial eye infections", "Conjunctivitis", "Keratitis", "Post-operative prophylaxis"],
    indication_bn: ["ব্যাকটেরিয়াল চোখের সংক্রমণ", "কনজাংটিভাইটিস", "কেরাটাইটিস", "অপারেশন পরবর্তী প্রতিরোধ"],
    alternatives: ["Tobramycin", "Nebcin", "Tobrasone"],
    price_range: { min: 45.0, max: 85.0 },
    prescription_required: true,
    common_dosage: "1-2 drops every 4 hours",
    common_dosage_bn: "প্রতি ৪ ঘণ্টায় ১-২ ড্রপ",
    side_effects: ["Eye irritation", "Burning", "Stinging", "Temporary vision changes"],
    side_effects_bn: ["চোখে জ্বালা", "জ্বালাপোড়া", "হুল ফোটানো", "সাময়িক দৃষ্টি পরিবর্তন"],
    contraindications: ["Hypersensitivity to tobramycin", "Viral eye infections"],
    contraindications_bn: ["টব্রামাইসিন অতি সংবেদনশীলতা", "ভাইরাল চোখের সংক্রমণ"],
    drug_interactions: ["Other aminoglycoside antibiotics"],
    drug_interactions_bn: ["অন্যান্য অ্যামিনোগ্লাইকোসাইড এন্টিবায়োটিক"],
    storage_instructions: "Store at room temperature. Protect from light.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো থেকে দূরে রাখুন।",
    warnings_precautions: ["For ophthalmic use only", "Prolonged use may lead to overgrowth of resistant organisms"],
    warnings_precautions_bn: ["শুধুমাত্র চোখের জন্য", "দীর্ঘ ব্যবহার প্রতিরোধী জীবাণু বৃদ্ধি করতে পারে"],
    pregnancy_lactation: {
      pregnancy_category: "B",
      pregnancy_info: "Generally safe during pregnancy",
      lactation_info: "Minimal systemic absorption",
      pregnancy_info_bn: "গর্ভাবস্থায় সাধারণত নিরাপদ",
      lactation_info_bn: "সিস্টেমিক শোষণ কম"
    },
    product_images: ["/images/medicines/tobrex-eye-drops.jpg"],
    keywords_bn: ["টব্রেক্স", "টব্রামাইসিন", "চোখের ইনফেকশন", "কেরাটাইটিস"]
  },

  // Anti-inflammatory Eye Drops
  {
    id: "pred-eye-001",
    generic_name: "Prednisolone Acetate",
    brand_name: "Pred Forte",
    generic_name_bn: "প্রেডনিসোলোন অ্যাসেটেট",
    brand_name_bn: "প্রেড ফোর্ট",
    manufacturer: "Allergan Bangladesh",
    manufacturer_bn: "অ্যালার্গান বাংলাদেশ",
    strength: "1%",
    form: "Eye Drops",
    form_bn: "চোখের ড্রপ",
    therapeutic_class: "Ophthalmic Corticosteroid",
    therapeutic_class_bn: "চোখের কর্টিকোস্টেরয়েড",
    indication: ["Allergic conjunctivitis", "Uveitis", "Keratitis", "Post-operative inflammation"],
    indication_bn: ["অ্যালার্জিক কনজাংটিভাইটিস", "ইউভিআইটিস", "কেরাটাইটিস", "অপারেশন পরবর্তী প্রদাহ"],
    alternatives: ["Prednisolone", "Omnipred", "Econopred"],
    price_range: { min: 65.0, max: 120.0 },
    prescription_required: true,
    common_dosage: "1-2 drops 2-4 times daily",
    common_dosage_bn: "দিনে ২-৪ বার ১-২ ড্রপ",
    side_effects: ["Increased eye pressure", "Delayed wound healing", "Cataract formation", "Secondary infections"],
    side_effects_bn: ["চোখের চাপ বৃদ্ধি", "ক্ষত সারা দেরি", "ছানি পড়া", "সেকেন্ডারী সংক্রমণ"],
    contraindications: ["Viral eye infections", "Fungal infections", "Mycobacterial infections"],
    contraindications_bn: ["ভাইরাল চোখের সংক্রমণ", "ছত্রাক সংক্রমণ", "মাইকোব্যাকটেরিয়াল সংক্রমণ"],
    drug_interactions: ["Anticholinesterases", "NSAIDs"],
    drug_interactions_bn: ["অ্যান্টিকোলিনেস্টারেজ", "এনএসএআইডি"],
    storage_instructions: "Store at 15-25°C. Shake well before use.",
    storage_instructions_bn: "১৫-২৫° সেলসিয়াসে রাখুন। ব্যবহারের আগে ভাল করে ঝাঁকান।",
    warnings_precautions: ["Monitor intraocular pressure", "Use for shortest duration possible", "Do not use if infection present"],
    warnings_precautions_bn: ["চোখের ভেতরের চাপ পরীক্ষা করুন", "সর্বনিম্ন সময়ের জন্য ব্যবহার করুন", "সংক্রমণ থাকলে ব্যবহার করবেন না"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Use with caution",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "সতর্কতার সাথে ব্যবহার করুন"
    },
    product_images: ["/images/medicines/pred-forte-drops.jpg"],
    keywords_bn: ["প্রেড ফোর্ট", "প্রেডনিসোলোন", "চোখের প্রদাহ", "ইউভিআইটিস"]
  },

  // Glaucoma Medications
  {
    id: "timol-001",
    generic_name: "Timolol Maleate",
    brand_name: "Timoptic",
    generic_name_bn: "টিমোলল ম্যালিয়েট",
    brand_name_bn: "টিমোপটিক",
    manufacturer: "Merck Bangladesh",
    manufacturer_bn: "মার্ক বাংলাদেশ",
    strength: "0.5%",
    form: "Eye Drops",
    form_bn: "চোখের ড্রপ",
    therapeutic_class: "Anti-glaucoma Agent",
    therapeutic_class_bn: "গ্লকোমা প্রতিরোধী",
    indication: ["Glaucoma", "Ocular hypertension", "Increased intraocular pressure"],
    indication_bn: ["গ্লকোমা", "চোখের উচ্চ চাপ", "চোখের ভেতরের চাপ বৃদ্ধি"],
    alternatives: ["Timolol", "Betoptic", "Cosopt"],
    price_range: { min: 85.0, max: 150.0 },
    prescription_required: true,
    common_dosage: "1 drop twice daily",
    common_dosage_bn: "দিনে দুইবার ১ ড্রপ",
    side_effects: ["Eye irritation", "Blurred vision", "Bradycardia", "Bronchospasm"],
    side_effects_bn: ["চোখে জ্বালা", "ঝাপসা দৃষ্টি", "হৃদস্পন্দন কমা", "ব্রঙ্কোস্প্যাজম"],
    contraindications: ["Asthma", "COPD", "Sinus bradycardia", "Heart block"],
    contraindications_bn: ["হাঁপানি", "সিওপিডি", "সাইনাস ব্র্যাডিকার্ডিয়া", "হার্ট ব্লক"],
    drug_interactions: ["Beta blockers", "Calcium channel blockers", "Digoxin"],
    drug_interactions_bn: ["বেটা ব্লকার", "ক্যালসিয়াম চ্যানেল ব্লকার", "ডিগক্সিন"],
    storage_instructions: "Store at room temperature. Protect from light.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো থেকে দূরে রাখুন।",
    warnings_precautions: ["Monitor heart rate and blood pressure", "Use with caution in cardiovascular disease"],
    warnings_precautions_bn: ["হৃদস্পন্দন ও রক্তচাপ পর্যবেক্ষণ করুন", "হৃদরোগে সতর্কতার সাথে ব্যবহার করুন"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Passes into breast milk",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "বুকের দুধে যায়"
    },
    product_images: ["/images/medicines/timoptic-drops.jpg"],
    keywords_bn: ["টিমোপটিক", "টিমোলল", "গ্লকোমা", "চোখের চাপ"]
  },

  // Artificial Tears
  {
    id: "hpmc-001",
    generic_name: "Hypromellose",
    brand_name: "Tears Naturale",
    generic_name_bn: "হাইপ্রোমেলোজ",
    brand_name_bn: "টিয়ার্স ন্যাচারাল",
    manufacturer: "Alcon Bangladesh",
    manufacturer_bn: "অ্যালকন বাংলাদেশ",
    strength: "0.3%",
    form: "Eye Drops",
    form_bn: "চোখের ড্রপ",
    therapeutic_class: "Artificial Tears",
    therapeutic_class_bn: "কৃত্রিম অশ্রু",
    indication: ["Dry eyes", "Keratoconjunctivitis sicca", "Contact lens discomfort", "Eye irritation"],
    indication_bn: ["শুকনো চোখ", "কেরাটোকনজাংটিভাইটিস সিক্কা", "কন্ট্যাক্ট লেন্স অস্বস্তি", "চোখে জ্বালা"],
    alternatives: ["Hypromellose", "Systane", "Refresh"],
    price_range: { min: 25.0, max: 50.0 },
    prescription_required: false,
    common_dosage: "1-2 drops as needed",
    common_dosage_bn: "প্রয়োজন অনুসারে ১-২ ড্রপ",
    side_effects: ["Temporary blurred vision", "Eye irritation", "Burning sensation"],
    side_effects_bn: ["সাময়িক ঝাপসা দৃষ্টি", "চোখে জ্বালা", "জ্বালাপোড়া"],
    contraindications: ["Hypersensitivity to hypromellose"],
    contraindications_bn: ["হাইপ্রোমেলোজ অতি সংবেদনশীলতা"],
    drug_interactions: ["No significant interactions"],
    drug_interactions_bn: ["কোনো গুরুত্বপূর্ণ ইন্টারঅ্যাকশন নেই"],
    storage_instructions: "Store at room temperature. Use within 28 days of opening.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। খোলার ২৮ দিনের মধ্যে ব্যবহার করুন।",
    warnings_precautions: ["Remove contact lenses before use", "Do not touch dropper to eye"],
    warnings_precautions_bn: ["ব্যবহারের আগে কন্ট্যাক্ট লেন্স খুলে নিন", "ড্রপারে চোখ লাগাবেন না"],
    pregnancy_lactation: {
      pregnancy_category: "A",
      pregnancy_info: "Safe during pregnancy",
      lactation_info: "Safe during breastfeeding",
      pregnancy_info_bn: "গর্ভাবস্থায় নিরাপদ",
      lactation_info_bn: "বুকের দুধ খাওয়ানোর সময় নিরাপদ"
    },
    product_images: ["/images/medicines/tears-naturale.jpg"],
    keywords_bn: ["টিয়ার্স ন্যাচারাল", "হাইপ্রোমেলোজ", "শুকনো চোখ", "কৃত্রিম অশ্রু"]
  },

  // Mydriatic/Cycloplegic
  {
    id: "atro-001",
    generic_name: "Atropine Sulfate",
    brand_name: "Atropine",
    generic_name_bn: "অ্যাট্রোপিন সালফেট",
    brand_name_bn: "অ্যাট্রোপিন",
    manufacturer: "Beximco Pharma",
    manufacturer_bn: "বেক্সিমকো ফার্মা",
    strength: "1%",
    form: "Eye Drops",
    form_bn: "চোখের ড্রপ",
    therapeutic_class: "Mydriatic/Cycloplegic",
    therapeutic_class_bn: "মাইড্রিয়াটিক/সাইক্লোপ্লেজিক",
    indication: ["Cycloplegic refraction", "Mydriasis for examination", "Treatment of uveitis", "Amblyopia therapy"],
    indication_bn: ["সাইক্লোপ্লেজিক রিফ্র্যাকশন", "পরীক্ষার জন্য তারার সম্প্রসারণ", "ইউভিআইটিস চিকিৎসা", "অ্যাম্বলায়োপিয়া থেরাপি"],
    alternatives: ["Atropine", "Cyclopentolate", "Homatropine"],
    price_range: { min: 20.0, max: 40.0 },
    prescription_required: true,
    common_dosage: "1 drop 1-2 times daily or as directed",
    common_dosage_bn: "দিনে ১-২ বার ১ ড্রপ বা নির্দেশ অনুসারে",
    side_effects: ["Photophobia", "Blurred vision", "Local irritation", "Systemic anticholinergic effects"],
    side_effects_bn: ["আলোর প্রতি ভীতি", "ঝাপসা দৃষ্টি", "স্থানীয় জ্বালা", "সিস্টেমিক অ্যান্টিকোলিনার্জিক প্রভাব"],
    contraindications: ["Narrow angle glaucoma", "Hypersensitivity to atropine"],
    contraindications_bn: ["সংকীর্ণ কোণ গ্লকোমা", "অ্যাট্রোপিন অতি সংবেদনশীলতা"],
    drug_interactions: ["Anticholinergic drugs", "Tricyclic antidepressants"],
    drug_interactions_bn: ["অ্যান্টিকোলিনার্জিক ওষুধ", "ট্রাইসাইক্লিক অ্যান্টিডিপ্রেসান্ট"],
    storage_instructions: "Store at room temperature. Protect from light.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো থেকে দূরে রাখুন।",
    warnings_precautions: ["Use sunglasses due to photophobia", "Monitor for systemic effects in children"],
    warnings_precautions_bn: ["আলোর ভীতির জন্য সানগ্লাস ব্যবহার করুন", "শিশুদের সিস্টেমিক প্রভাব পর্যবেক্ষণ করুন"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Use with caution",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "সতর্কতার সাথে ব্যবহার করুন"
    },
    product_images: ["/images/medicines/atropine-eye-drops.jpg"],
    keywords_bn: ["অ্যাট্রোপিন", "তারা সম্প্রসারণ", "চোখের পরীক্ষা", "ইউভিআইটিস"]
  }
];

export default ophthalmologicalDatabase;