/**
 * DERMATOLOGICAL MEDICINES DATABASE
 * Comprehensive collection of dermatological medicines available in Bangladesh
 */

import { MedicineKnowledgeEntry } from './medicine-knowledge-base';

export const dermatologicalDatabase: MedicineKnowledgeEntry[] = [
  // Topical Antibiotics
  {
    id: "mup-001",
    generic_name: "Mupirocin",
    brand_name: "Bactroban",
    generic_name_bn: "মুপিরোসিন",
    brand_name_bn: "ব্যাক্ট্রোবান",
    manufacturer: "GSK Bangladesh",
    manufacturer_bn: "জিএসকে বাংলাদেশ",
    strength: "2%",
    form: "Ointment",
    form_bn: "মলম",
    therapeutic_class: "Topical Antibiotic",
    therapeutic_class_bn: "বাহ্যিক এন্টিবায়োটিক",
    indication: ["Bacterial skin infections", "Impetigo", "Folliculitis", "Minor cuts and wounds"],
    indication_bn: ["ব্যাকটেরিয়া চর্মরোগ", "ইমপেটিগো", "ফলিকুলাইটিস", "ছোট কাটা ও ক্ষত"],
    alternatives: ["Mupirocin", "Centany", "Bactoderm"],
    price_range: { min: 25.0, max: 45.0 },
    prescription_required: false,
    common_dosage: "Apply thin layer 2-3 times daily",
    common_dosage_bn: "দিনে ২-৩ বার পাতলা স্তর লাগান",
    side_effects: ["Local irritation", "Burning sensation", "Itching", "Rash"],
    side_effects_bn: ["স্থানীয় জ্বালা", "জ্বালাপোড়া", "চুলকানি", "র‍্যাশ"],
    contraindications: ["Hypersensitivity to mupirocin"],
    contraindications_bn: ["মুপিরোসিনে অতি সংবেদনশীলতা"],
    drug_interactions: ["No significant interactions"],
    drug_interactions_bn: ["কোনো গুরুত্বপূর্ণ ইন্টারঅ্যাকশন নেই"],
    storage_instructions: "Store at room temperature. Do not freeze.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। হিমায়িত করবেন না।",
    warnings_precautions: ["For external use only", "Avoid contact with eyes", "Do not use for more than 10 days"],
    warnings_precautions_bn: ["শুধুমাত্র বাহ্যিক ব্যবহারে", "চোখে যেন না লাগে", "১০ দিনের বেশি ব্যবহার করবেন না"],
    pregnancy_lactation: {
      pregnancy_category: "B",
      pregnancy_info: "Safe for topical use during pregnancy",
      lactation_info: "Minimal systemic absorption",
      pregnancy_info_bn: "গর্ভাবস্থায় বাহ্যিক ব্যবহার নিরাপদ",
      lactation_info_bn: "সিস্টেমিক শোষণ কম"
    },
    product_images: ["/images/medicines/bactroban-ointment.jpg"],
    keywords_bn: ["ব্যাক্ট্রোবান", "মুপিরোসিন", "চর্মরোগ", "ক্ষত"]
  },

  // Antifungals
  {
    id: "clot-001",
    generic_name: "Clotrimazole",
    brand_name: "Candid",
    generic_name_bn: "ক্লোট্রিমাজল",
    brand_name_bn: "ক্যান্ডিড",
    manufacturer: "Glenmark Pharmaceuticals",
    manufacturer_bn: "গ্লেনমার্ক ফার্মাসিউটিক্যালস",
    strength: "1%",
    form: "Cream",
    form_bn: "ক্রিম",
    therapeutic_class: "Topical Antifungal",
    therapeutic_class_bn: "বাহ্যিক ছত্রাকনাশক",
    indication: ["Fungal skin infections", "Athlete's foot", "Ringworm", "Candidiasis"],
    indication_bn: ["ছত্রাক চর্মরোগ", "অ্যাথলেট ফুট", "দাদ", "ক্যান্ডিডিয়াসিস"],
    alternatives: ["Clotrimazole", "Lotrimin", "Mycelex"],
    price_range: { min: 15.0, max: 30.0 },
    prescription_required: false,
    common_dosage: "Apply twice daily for 2-4 weeks",
    common_dosage_bn: "২-৪ সপ্তাহ দিনে দুইবার লাগান",
    side_effects: ["Local irritation", "Burning", "Stinging", "Redness"],
    side_effects_bn: ["স্থানীয় জ্বালা", "জ্বালাপোড়া", "হুল ফোটানো", "লালভাব"],
    contraindications: ["Hypersensitivity to clotrimazole"],
    contraindications_bn: ["ক্লোট্রিমাজলে অতি সংবেদনশীলতা"],
    drug_interactions: ["No significant topical interactions"],
    drug_interactions_bn: ["কোনো গুরুত্বপূর্ণ বাহ্যিক ইন্টারঅ্যাকশন নেই"],
    storage_instructions: "Store at room temperature. Keep tube tightly closed.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। টিউব শক্ত করে বন্ধ রাখুন।",
    warnings_precautions: ["For external use only", "Avoid contact with eyes", "Continue for 1 week after symptoms clear"],
    warnings_precautions_bn: ["শুধুমাত্র বাহ্যিক ব্যবহারে", "চোখে যেন না লাগে", "লক্ষণ চলে যাওয়ার ১ সপ্তাহ পর পর্যন্ত চালিয়ে যান"],
    pregnancy_lactation: {
      pregnancy_category: "B",
      pregnancy_info: "Safe for topical use",
      lactation_info: "Minimal systemic absorption",
      pregnancy_info_bn: "বাহ্যিক ব্যবহার নিরাপদ",
      lactation_info_bn: "সিস্টেমিক শোষণ কম"
    },
    product_images: ["/images/medicines/candid-cream.jpg"],
    keywords_bn: ["ক্যান্ডিড", "ক্লোট্রিমাজল", "দাদ", "ছত্রাক"]
  },

  // Corticosteroids
  {
    id: "beta-001",
    generic_name: "Betamethasone",
    brand_name: "Betnovate",
    generic_name_bn: "বেটামেথাসন",
    brand_name_bn: "বেটনোভেট",
    manufacturer: "GSK Bangladesh",
    manufacturer_bn: "জিএসকে বাংলাদেশ",
    strength: "0.1%",
    form: "Cream",
    form_bn: "ক্রিম",
    therapeutic_class: "Topical Corticosteroid",
    therapeutic_class_bn: "বাহ্যিক কর্টিকোস্টেরয়েড",
    indication: ["Eczema", "Psoriasis", "Dermatitis", "Allergic skin conditions"],
    indication_bn: ["একজিমা", "সোরিয়াসিস", "ডার্মাটাইটিস", "অ্যালার্জিক চর্মরোগ"],
    alternatives: ["Betnovate", "Diprosone", "Celestone"],
    price_range: { min: 20.0, max: 40.0 },
    prescription_required: true,
    common_dosage: "Apply thin layer 1-2 times daily",
    common_dosage_bn: "দিনে ১-২ বার পাতলা স্তর লাগান",
    side_effects: ["Skin thinning", "Stretch marks", "Local irritation", "Increased hair growth"],
    side_effects_bn: ["চামড়া পাতলা হওয়া", "স্ট্রেচ মার্ক", "স্থানীয় জ্বালা", "লোম বৃদ্ধি"],
    contraindications: ["Viral skin infections", "Bacterial infections", "Fungal infections"],
    contraindications_bn: ["ভাইরাল চর্মরোগ", "ব্যাকটেরিয়াল সংক্রমণ", "ছত্রাক সংক্রমণ"],
    drug_interactions: ["No significant topical interactions"],
    drug_interactions_bn: ["কোনো গুরুত্বপূর্ণ বাহ্যিক ইন্টারঅ্যাকশন নেই"],
    storage_instructions: "Store at room temperature. Keep away from heat.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। গরম থেকে দূরে রাখুন।",
    warnings_precautions: ["Do not use on face for extended periods", "Avoid occlusive dressings", "Gradual discontinuation"],
    warnings_precautions_bn: ["মুখে দীর্ঘদিন ব্যবহার করবেন না", "ঢেকে রাখা পট্টি এড়িয়ে চলুন", "ধীরে ধীরে বন্ধ করুন"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Use with caution",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "সতর্কতার সাথে ব্যবহার করুন"
    },
    product_images: ["/images/medicines/betnovate-cream.jpg"],
    keywords_bn: ["বেটনোভেট", "বেটামেথাসন", "একজিমা", "চুলকানি"]
  },

  // Antiseptics
  {
    id: "povi-001",
    generic_name: "Povidone Iodine",
    brand_name: "Betadine",
    generic_name_bn: "পভিডন আয়োডিন",
    brand_name_bn: "বেটাডিন",
    manufacturer: "Mundipharma Bangladesh",
    manufacturer_bn: "মুন্ডিফার্মা বাংলাদেশ",
    strength: "10%",
    form: "Solution",
    form_bn: "সল্যুশন",
    therapeutic_class: "Topical Antiseptic",
    therapeutic_class_bn: "বাহ্যিক জীবাণুনাশক",
    indication: ["Wound disinfection", "Pre-operative skin preparation", "Minor cuts", "Burns"],
    indication_bn: ["ক্ষত জীবাণুমুক্তকরণ", "অপারেশনের আগে চামড়া প্রস্তুতি", "ছোট কাটা", "পোড়া"],
    alternatives: ["Povidone Iodine", "Wokadine", "Pyodine"],
    price_range: { min: 12.0, max: 25.0 },
    prescription_required: false,
    common_dosage: "Apply to affected area 1-3 times daily",
    common_dosage_bn: "আক্রান্ত স্থানে দিনে ১-৩ বার লাগান",
    side_effects: ["Local irritation", "Allergic reactions", "Skin staining"],
    side_effects_bn: ["স্থানীয় জ্বালা", "অ্যালার্জিক প্রতিক্রিয়া", "চামড়া দাগ"],
    contraindications: ["Iodine hypersensitivity", "Thyroid disorders", "Renal impairment"],
    contraindications_bn: ["আয়োডিন অতি সংবেদনশীলতা", "থাইরয়েড সমস্যা", "কিডনি সমস্যা"],
    drug_interactions: ["Lithium", "Antiseptic solutions"],
    drug_interactions_bn: ["লিথিয়াম", "জীবাণুনাশক সল্যুশন"],
    storage_instructions: "Store at room temperature. Protect from light.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো থেকে দূরে রাখুন।",
    warnings_precautions: ["Do not use with other antiseptics", "May stain clothing", "Avoid contact with eyes"],
    warnings_precautions_bn: ["অন্য জীবাণুনাশকের সাথে ব্যবহার করবেন না", "কাপড়ে দাগ হতে পারে", "চোখে যেন না লাগে"],
    pregnancy_lactation: {
      pregnancy_category: "D",
      pregnancy_info: "Avoid during pregnancy due to iodine absorption",
      lactation_info: "Contraindicated during breastfeeding",
      pregnancy_info_bn: "আয়োডিন শোষণের কারণে গর্ভাবস্থায় এড়িয়ে চলুন",
      lactation_info_bn: "বুকের দুধ খাওয়ানোর সময় নিষিদ্ধ"
    },
    product_images: ["/images/medicines/betadine-solution.jpg"],
    keywords_bn: ["বেটাডিন", "পভিডন আয়োডিন", "জীবাণুনাশক", "ক্ষত"]
  },

  // Acne Treatments
  {
    id: "tret-001",
    generic_name: "Tretinoin",
    brand_name: "Retin-A",
    generic_name_bn: "ট্রেটিনয়িন",
    brand_name_bn: "রেটিন-এ",
    manufacturer: "Janssen Bangladesh",
    manufacturer_bn: "জ্যানসেন বাংলাদেশ",
    strength: "0.025%",
    form: "Cream",
    form_bn: "ক্রিম",
    therapeutic_class: "Topical Retinoid",
    therapeutic_class_bn: "বাহ্যিক রেটিনয়েড",
    indication: ["Acne vulgaris", "Photo-aged skin", "Fine wrinkles", "Hyperpigmentation"],
    indication_bn: ["ব্রণ", "বয়স্ক চামড়া", "সূক্ষ্ম বলিরেখা", "হাইপারপিগমেন্টেশন"],
    alternatives: ["Tretinoin", "A-Ret", "Retacnyl"],
    price_range: { min: 35.0, max: 65.0 },
    prescription_required: true,
    common_dosage: "Apply thin layer at bedtime every other day initially",
    common_dosage_bn: "প্রথমে একদিন পরপর রাতে পাতলা স্তর লাগান",
    side_effects: ["Skin irritation", "Redness", "Peeling", "Photosensitivity", "Dryness"],
    side_effects_bn: ["চামড়া জ্বালা", "লালভাব", "খোসা ছাড়া", "আলোর প্রতি সংবেদনশীলতা", "শুষ্কতা"],
    contraindications: ["Pregnancy", "Hypersensitivity", "Eczema", "Sunburn"],
    contraindications_bn: ["গর্ভাবস্থা", "অতি সংবেদনশীলতা", "একজিমা", "রোদে পোড়া"],
    drug_interactions: ["Benzoyl peroxide", "Sulfur", "Salicylic acid"],
    drug_interactions_bn: ["বেনজয়েল পারক্সাইড", "সালফার", "স্যালিসাইলিক অ্যাসিড"],
    storage_instructions: "Store at room temperature. Protect from light and heat.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো ও গরম থেকে দূরে রাখুন।",
    warnings_precautions: ["Use sunscreen during treatment", "Start with low frequency", "Avoid waxing treated areas"],
    warnings_precautions_bn: ["চিকিৎসার সময় সানস্ক্রিন ব্যবহার করুন", "কম ঘন ঘন দিয়ে শুরু করুন", "চিকিৎসা করা জায়গায় ওয়াক্সিং এড়িয়ে চলুন"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Contraindicated in pregnancy",
      lactation_info: "Use with caution",
      pregnancy_info_bn: "গর্ভাবস্থায় নিষিদ্ধ",
      lactation_info_bn: "সতর্কতার সাথে ব্যবহার করুন"
    },
    product_images: ["/images/medicines/retin-a-cream.jpg"],
    keywords_bn: ["রেটিন-এ", "ট্রেটিনয়িন", "ব্রণ", "বলিরেখা"]
  },

  // Anti-inflammatory
  {
    id: "diclo-gel-001",
    generic_name: "Diclofenac Sodium",
    brand_name: "Voltaren Gel",
    generic_name_bn: "ডাইক্লোফেনাক সোডিয়াম",
    brand_name_bn: "ভোলটারেন জেল",
    manufacturer: "Novartis Bangladesh",
    manufacturer_bn: "নোভার্টিস বাংলাদেশ",
    strength: "1%",
    form: "Gel",
    form_bn: "জেল",
    therapeutic_class: "Topical NSAID",
    therapeutic_class_bn: "বাহ্যিক এনএসএআইডি",
    indication: ["Joint pain", "Muscle pain", "Sports injuries", "Arthritis"],
    indication_bn: ["জয়েন্টের ব্যথা", "পেশির ব্যথা", "খেলাধুলার আঘাত", "বাত"],
    alternatives: ["Diclofenac gel", "Volini", "Dynapar"],
    price_range: { min: 45.0, max: 85.0 },
    prescription_required: false,
    common_dosage: "Apply and rub gently 3-4 times daily",
    common_dosage_bn: "দিনে ৩-৪ বার লাগিয়ে আলতো করে মালিশ করুন",
    side_effects: ["Local irritation", "Rash", "Itching", "Burning sensation"],
    side_effects_bn: ["স্থানীয় জ্বালা", "র‍্যাশ", "চুলকানি", "জ্বালাপোড়া"],
    contraindications: ["Hypersensitivity to NSAIDs", "Open wounds", "Infected skin"],
    contraindications_bn: ["এনএসএআইডি অতি সংবেদনশীলতা", "খোলা ক্ষত", "সংক্রমিত চামড়া"],
    drug_interactions: ["Oral NSAIDs", "Warfarin", "Lithium"],
    drug_interactions_bn: ["মুখে খাওয়ার এনএসএআইডি", "ওয়ারফারিন", "লিথিয়াম"],
    storage_instructions: "Store at room temperature. Keep tube tightly closed.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। টিউব শক্ত করে বন্ধ রাখুন।",
    warnings_precautions: ["For external use only", "Wash hands after application", "Avoid contact with eyes and mucous membranes"],
    warnings_precautions_bn: ["শুধুমাত্র বাহ্যিক ব্যবহারে", "ব্যবহারের পর হাত ধুয়ে নিন", "চোখ ও মিউকাস মেমব্রেনে যেন না লাগে"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Use only if benefits outweigh risks",
      lactation_info: "Minimal systemic absorption",
      pregnancy_info_bn: "উপকারিতা ঝুঁকির চেয়ে বেশি হলেই ব্যবহার করুন",
      lactation_info_bn: "সিস্টেমিক শোষণ কম"
    },
    product_images: ["/images/medicines/voltaren-gel.jpg"],
    keywords_bn: ["ভোলটারেন জেল", "ডাইক্লোফেনাক", "ব্যথা", "বাত"]
  }
];

export default dermatologicalDatabase;