/**
 * GYNECOLOGICAL & CONTRACEPTIVE MEDICINES DATABASE
 * Comprehensive collection of gynecological and contraceptive medicines available in Bangladesh
 */

import { MedicineKnowledgeEntry } from './medicine-knowledge-base';

export const gynecologicalDatabase: MedicineKnowledgeEntry[] = [
  // Oral Contraceptives
  {
    id: "ethinyl-001",
    generic_name: "Ethinylestradiol + Levonorgestrel",
    brand_name: "Microgynon",
    generic_name_bn: "ইথিনাইলইস্ট্রাডায়ল + লেভোনরজেস্ট্রেল",
    brand_name_bn: "মাইক্রোগাইনন",
    manufacturer: "Bayer Bangladesh",
    manufacturer_bn: "বায়ার বাংলাদেশ",
    strength: "30mcg + 150mcg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Combined Oral Contraceptive",
    therapeutic_class_bn: "সমন্বিত জন্মনিয়ন্ত্রণ বড়ি",
    indication: ["Contraception", "Menstrual regulation", "Dysmenorrhea", "Acne treatment"],
    indication_bn: ["জন্মনিয়ন্ত্রণ", "মাসিক নিয়ন্ত্রণ", "ডিসমেনোরিয়া", "ব্রণের চিকিৎসা"],
    alternatives: ["Yasmin", "Diane-35", "Nordette"],
    price_range: { min: 45.0, max: 85.0 },
    prescription_required: true,
    common_dosage: "1 tablet daily for 21 days, then 7-day break",
    common_dosage_bn: "২১ দিন দৈনিক ১টি, তারপর ৭ দিন বিরতি",
    side_effects: ["Nausea", "Breast tenderness", "Weight gain", "Mood changes", "Headache"],
    side_effects_bn: ["বমি বমি ভাব", "স্তনে ব্যথা", "ওজন বৃদ্ধি", "মুডের পরিবর্তন", "মাথাব্যথা"],
    contraindications: ["Pregnancy", "Thromboembolism", "Liver disease", "Breast cancer", "Smoking over 35"],
    contraindications_bn: ["গর্ভাবস্থা", "রক্ত জমাট", "লিভার রোগ", "স্তন ক্যান্সার", "৩৫ বছরের ওপরে ধূমপান"],
    drug_interactions: ["Antibiotics", "Anticonvulsants", "Rifampicin", "St. John's wort"],
    drug_interactions_bn: ["এন্টিবায়োটিক", "খিঁচুনি নিবারক", "রিফামপিসিন", "সেন্ট জনস ওয়ার্ট"],
    storage_instructions: "Store at room temperature. Protect from moisture.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আর্দ্রতা থেকে দূরে রাখুন।",
    warnings_precautions: ["Increased risk of blood clots", "Regular gynecological checkups", "Report unusual bleeding"],
    warnings_precautions_bn: ["রক্ত জমাটের ঝুঁকি বৃদ্ধি", "নিয়মিত গাইনি চেকআপ", "অস্বাভাবিক রক্তপাত জানান"],
    pregnancy_lactation: {
      pregnancy_category: "X",
      pregnancy_info: "Contraindicated in pregnancy",
      lactation_info: "May reduce milk production",
      pregnancy_info_bn: "গর্ভাবস্থায় নিষিদ্ধ",
      lactation_info_bn: "দুধ উৎপাদন কমতে পারে"
    },
    product_images: ["/images/medicines/microgynon-21.jpg"],
    keywords_bn: ["মাইক্রোগাইনন", "জন্মনিয়ন্ত্রণ", "বড়ি", "মাসিক"]
  },

  // Emergency Contraceptives
  {
    id: "levo-001",
    generic_name: "Levonorgestrel",
    brand_name: "Postinor-2",
    generic_name_bn: "লেভোনরজেস্ট্রেল",
    brand_name_bn: "পোস্টিনর-২",
    manufacturer: "Gedeon Richter Bangladesh",
    manufacturer_bn: "গিডিয়ন রিক্টার বাংলাদেশ",
    strength: "1.5mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Emergency Contraceptive",
    therapeutic_class_bn: "জরুরি জন্মনিয়ন্ত্রণ",
    indication: ["Emergency contraception", "Prevention of pregnancy after unprotected intercourse"],
    indication_bn: ["জরুরি জন্মনিয়ন্ত্রণ", "অনিরাপদ সহবাসের পর গর্ভাবস্থা প্রতিরোধ"],
    alternatives: ["Plan B", "I-Pill", "Unwanted 72"],
    price_range: { min: 80.0, max: 150.0 },
    prescription_required: false,
    common_dosage: "1 tablet as soon as possible within 72 hours",
    common_dosage_bn: "৭২ ঘণ্টার মধ্যে যত তাড়াতাড়ি সম্ভব ১টি ট্যাবলেট",
    side_effects: ["Nausea", "Vomiting", "Fatigue", "Irregular bleeding", "Breast tenderness"],
    side_effects_bn: ["বমি বমি ভাব", "বমি", "ক্লান্তি", "অনিয়মিত রক্তপাত", "স্তনে ব্যথা"],
    contraindications: ["Pregnancy", "Hypersensitivity", "Severe liver disease"],
    contraindications_bn: ["গর্ভাবস্থা", "অতি সংবেদনশীলতা", "গুরুতর লিভার রোগ"],
    drug_interactions: ["CYP3A4 inducers", "Rifampicin", "Carbamazepine"],
    drug_interactions_bn: ["সিওয়াইপি৩এ৪ ইনডিউসার", "রিফামপিসিন", "কার্বামাজেপিন"],
    storage_instructions: "Store at room temperature. Protect from light and moisture.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আলো ও আর্দ্রতা থেকে দূরে রাখুন।",
    warnings_precautions: ["Not for routine contraception", "Less effective after 72 hours", "May cause menstrual changes"],
    warnings_precautions_bn: ["নিয়মিত জন্মনিয়ন্ত্রণের জন্য নয়", "৭২ ঘণ্টা পর কম কার্যকর", "মাসিকের পরিবর্তন হতে পারে"],
    pregnancy_lactation: {
      pregnancy_category: "X",
      pregnancy_info: "Contraindicated if already pregnant",
      lactation_info: "Compatible with breastfeeding",
      pregnancy_info_bn: "ইতিমধ্যে গর্ভবতী হলে নিষিদ্ধ",
      lactation_info_bn: "বুকের দুধ খাওয়ানোর সাথে সামঞ্জস্যপূর্ণ"
    },
    product_images: ["/images/medicines/postinor-2.jpg"],
    keywords_bn: ["পোস্টিনর-২", "জরুরি", "জন্মনিয়ন্ত্রণ", "আইপিল"]
  },

  // Hormone Replacement Therapy
  {
    id: "estra-001",
    generic_name: "Estradiol",
    brand_name: "Estrofem",
    generic_name_bn: "এস্ট্রাডায়ল",
    brand_name_bn: "এস্ট্রোফেম",
    manufacturer: "Novo Nordisk Bangladesh",
    manufacturer_bn: "নভো নরডিস্ক বাংলাদেশ",
    strength: "2mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Hormone Replacement Therapy",
    therapeutic_class_bn: "হরমোন রিপ্লেসমেন্ট থেরাপি",
    indication: ["Menopausal symptoms", "Osteoporosis prevention", "Hypogonadism", "Hormone deficiency"],
    indication_bn: ["মেনোপজের লক্ষণ", "অস্টিওপোরোসিস প্রতিরোধ", "হাইপোগোনাডিজম", "হরমোনের ঘাটতি"],
    alternatives: ["Premarin", "Climara", "Vivelle"],
    price_range: { min: 180.0, max: 350.0 },
    prescription_required: true,
    common_dosage: "1-2mg once daily",
    common_dosage_bn: "দিনে একবার ১-২ মিগ্রা",
    side_effects: ["Breast tenderness", "Nausea", "Headache", "Fluid retention", "Mood changes"],
    side_effects_bn: ["স্তনে ব্যথা", "বমি বমি ভাব", "মাথাব্যথা", "পানি আটকে থাকা", "মুডের পরিবর্তন"],
    contraindications: ["Breast cancer", "Endometrial cancer", "Thromboembolism", "Liver disease"],
    contraindications_bn: ["স্তন ক্যান্সার", "এন্ডোমেট্রিয়াল ক্যান্সার", "রক্ত জমাট", "লিভার রোগ"],
    drug_interactions: ["Warfarin", "Carbamazepine", "Rifampicin", "Thyroid hormones"],
    drug_interactions_bn: ["ওয়ারফারিন", "কার্বামাজেপিন", "রিফামপিসিন", "থাইরয়েড হরমোন"],
    storage_instructions: "Store at room temperature. Keep in original package.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। মূল প্যাকেজে রাখুন।",
    warnings_precautions: ["Regular breast and gynecological exams", "Monitor for thrombosis", "Lowest effective dose"],
    warnings_precautions_bn: ["নিয়মিত স্তন ও গাইনি পরীক্ষা", "রক্ত জমাট পর্যবেক্ষণ", "সর্বনিম্ন কার্যকর ডোজ"],
    pregnancy_lactation: {
      pregnancy_category: "X",
      pregnancy_info: "Contraindicated in pregnancy",
      lactation_info: "May suppress lactation",
      pregnancy_info_bn: "গর্ভাবস্থায় নিষিদ্ধ",
      lactation_info_bn: "দুধ উৎপাদন কমতে পারে"
    },
    product_images: ["/images/medicines/estrofem-2mg.jpg"],
    keywords_bn: ["এস্ট্রোফেম", "এস্ট্রাডায়ল", "মেনোপজ", "হরমোন"]
  },

  // Antifungals (Vaginal)
  {
    id: "fluco-vag-001",
    generic_name: "Fluconazole",
    brand_name: "Diflucan",
    generic_name_bn: "ফ্লুকোনাজোল",
    brand_name_bn: "ডিফ্লুক্যান",
    manufacturer: "Pfizer Bangladesh",
    manufacturer_bn: "ফাইজার বাংলাদেশ",
    strength: "150mg",
    form: "Capsule",
    form_bn: "ক্যাপসুল",
    therapeutic_class: "Antifungal",
    therapeutic_class_bn: "ছত্রাকনাশক",
    indication: ["Vaginal candidiasis", "Vulvovaginal candidiasis", "Recurrent yeast infections"],
    indication_bn: ["যোনি ক্যান্ডিডিয়াসিস", "ভালভোভ্যাজাইনাল ক্যান্ডিডিয়াসিস", "পুনরাবৃত্ত ইস্ট সংক্রমণ"],
    alternatives: ["Fluconazole", "Canesten", "Gynazole"],
    price_range: { min: 15.0, max: 25.0 },
    prescription_required: false,
    common_dosage: "150mg single dose",
    common_dosage_bn: "১৫০ মিগ্রা একক ডোজ",
    side_effects: ["Nausea", "Headache", "Abdominal pain", "Diarrhea", "Dizziness"],
    side_effects_bn: ["বমি বমি ভাব", "মাথাব্যথা", "পেটব্যথা", "ডায়রিয়া", "মাথা ঘোরা"],
    contraindications: ["Hypersensitivity to fluconazole", "Concurrent terfenadine", "Severe liver disease"],
    contraindications_bn: ["ফ্লুকোনাজল অতি সংবেদনশীলতা", "টারফেনাডিনের সাথে", "গুরুতর লিভার রোগ"],
    drug_interactions: ["Warfarin", "Phenytoin", "Cyclosporine", "Oral hypoglycemics"],
    drug_interactions_bn: ["ওয়ারফারিন", "ফেনাইটয়িন", "সাইক্লোস্পরিন", "ডায়াবেটিসের ওষুধ"],
    storage_instructions: "Store at room temperature. Protect from moisture.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় রাখুন। আর্দ্রতা থেকে দূরে রাখুন।",
    warnings_precautions: ["Monitor liver function with prolonged use", "May interact with many drugs"],
    warnings_precautions_bn: ["দীর্ঘ ব্যবহারে লিভার পরীক্ষা করুন", "অনেক ওষুধের সাথে ইন্টারঅ্যাক্ট করতে পারে"],
    pregnancy_lactation: {
      pregnancy_category: "C",
      pregnancy_info: "Single dose generally safe",
      lactation_info: "Passes into breast milk",
      pregnancy_info_bn: "একক ডোজ সাধারণত নিরাপদ",
      lactation_info_bn: "বুকের দুধে যায়"
    },
    product_images: ["/images/medicines/diflucan-150mg.jpg"],
    keywords_bn: ["ডিফ্লুক্যান", "ফ্লুকোনাজোল", "যোনি ছত্রাক", "ইস্ট ইনফেকশন"]
  },

  // Iron Supplements
  {
    id: "iron-fol-001",
    generic_name: "Ferrous Sulfate + Folic Acid",
    brand_name: "Fefol",
    generic_name_bn: "ফেরাস সালফেট + ফলিক অ্যাসিড",
    brand_name_bn: "ফিফল",
    manufacturer: "GSK Bangladesh",
    manufacturer_bn: "জিএসকে বাংলাদেশ",
    strength: "150mg + 0.5mg",
    form: "Capsule",
    form_bn: "ক্যাপসুল",
    therapeutic_class: "Iron and Folic Acid Supplement",
    therapeutic_class_bn: "আয়রন ও ফলিক অ্যাসিড সাপ্লিমেন্ট",
    indication: ["Iron deficiency anemia", "Pregnancy anemia", "Nutritional anemia", "Folic acid deficiency"],
    indication_bn: ["আয়রনের ঘাটতিজনিত রক্তশূন্যতা", "গর্ভাবস্থায় রক্তশূন্যতা", "পুষ্টিহীনতাজনিত রক্তশূন্যতা", "ফলিক অ্যাসিডের ঘাটতি"],
    alternatives: ["Ferrous sulfate", "Iron-folic", "Hemfer"],
    price_range: { min: 3.0, max: 6.0 },
    prescription_required: false,
    common_dosage: "1 capsule daily with food",
    common_dosage_bn: "খাবারের সাথে দিনে ১টি ক্যাপসুল",
    side_effects: ["Constipation", "Nausea", "Dark stools", "Abdominal discomfort", "Metallic taste"],
    side_effects_bn: ["কব্জি", "বমি বমি ভাব", "কালো পায়খানা", "পেটে অস্বস্তি", "ধাতব স্বাদ"],
    contraindications: ["Hemochromatosis", "Hemosiderosis", "Thalassemia", "Lead anemia"],
    contraindications_bn: ["হিমোক্রোমাটোসিস", "হিমোসিডেরোসিস", "থ্যালাসেমিয়া", "লেড অ্যানিমিয়া"],
    drug_interactions: ["Tetracyclines", "Antacids", "Calcium supplements", "Tea/coffee"],
    drug_interactions_bn: ["টেট্রাসাইক্লিন", "অ্যান্টাসিড", "ক্যালসিয়াম সাপ্লিমেন্ট", "চা/কফি"],
    storage_instructions: "Store in dry place at room temperature. Keep away from children.",
    storage_instructions_bn: "ঘরের তাপমাত্রায় শুকনো জায়গায় রাখুন। শিশুদের নাগালের বাইরে রাখুন।",
    warnings_precautions: ["Take on empty stomach for better absorption", "May cause constipation", "Avoid with dairy products"],
    warnings_precautions_bn: ["ভাল শোষণের জন্য খালি পেটে নিন", "কব্জি হতে পারে", "দুগ্ধজাত খাবার এড়িয়ে চলুন"],
    pregnancy_lactation: {
      pregnancy_category: "A",
      pregnancy_info: "Safe and recommended during pregnancy",
      lactation_info: "Safe during breastfeeding",
      pregnancy_info_bn: "গর্ভাবস্থায় নিরাপদ ও প্রয়োজনীয়",
      lactation_info_bn: "বুকের দুধ খাওয়ানোর সময় নিরাপদ"
    },
    product_images: ["/images/medicines/fefol-capsule.jpg"],
    keywords_bn: ["ফিফল", "আয়রন", "ফলিক অ্যাসিড", "রক্তশূন্যতা"]
  },

  // Uterine Tonics
  {
    id: "meth-001",
    generic_name: "Methylergonovine",
    brand_name: "Methergine",
    generic_name_bn: "মিথাইলআর্গোনভিন",
    brand_name_bn: "মেথারজিন",
    manufacturer: "Novartis Bangladesh",
    manufacturer_bn: "নোভার্টিস বাংলাদেশ",
    strength: "0.2mg",
    form: "Tablet",
    form_bn: "ট্যাবলেট",
    therapeutic_class: "Ergot Alkaloid",
    therapeutic_class_bn: "আর্গট অ্যালক্যালয়েড",
    indication: ["Postpartum hemorrhage", "Uterine atony", "Incomplete abortion", "Subinvolution of uterus"],
    indication_bn: ["প্রসব পরবর্তী রক্তক্ষরণ", "জরায়ু অবসাদ", "অসম্পূর্ণ গর্ভপাত", "জরায়ুর সাবইনভলিউশন"],
    alternatives: ["Ergometrine", "Oxytocin", "Carbetocin"],
    price_range: { min: 8.0, max: 15.0 },
    prescription_required: true,
    common_dosage: "0.2mg 3-4 times daily for 2-7 days",
    common_dosage_bn: "২-৭ দিন দিনে ৩-৪ বার ০.২ মিগ্রা",
    side_effects: ["Nausea", "Vomiting", "Hypertension", "Headache", "Abdominal cramping"],
    side_effects_bn: ["বমি বমি ভাব", "বমি", "উচ্চ রক্তচাপ", "মাথাব্যথা", "পেটে খিঁচুনি"],
    contraindications: ["Pregnancy", "Hypertension", "Coronary artery disease", "Peripheral vascular disease"],
    contraindications_bn: ["গর্ভাবস্থা", "উচ্চ রক্তচাপ", "করোনারী আর্টারী ডিজিজ", "পেরিফেরাল ভাস্কুলার ডিজিজ"],
    drug_interactions: ["Beta blockers", "Sympathomimetics", "CYP3A4 inhibitors"],
    drug_interactions_bn: ["বেটা ব্লকার", "সিম্প্যাথোমাইমেটিক", "সিওয়াইপি৩এ৪ ইনহিবিটর"],
    storage_instructions: "Store in refrigerator (2-8°C). Protect from light.",
    storage_instructions_bn: "ফ্রিজে (২-৮° সেলসিয়াস) রাখুন। আলো থেকে দূরে রাখুন।",
    warnings_precautions: ["Monitor blood pressure", "Use only after delivery of placenta", "Contraindicated in eclampsia"],
    warnings_precautions_bn: ["রক্তচাপ পর্যবেক্ষণ করুন", "গর্ভফুল বের হওয়ার পরই ব্যবহার করুন", "একলাম্পসিয়ায় নিষিদ্ধ"],
    pregnancy_lactation: {
      pregnancy_category: "X",
      pregnancy_info: "Contraindicated during pregnancy",
      lactation_info: "Passes into breast milk, may suppress lactation",
      pregnancy_info_bn: "গর্ভাবস্থায় নিষিদ্ধ",
      lactation_info_bn: "বুকের দুধে যায়, দুধ উৎপাদন কমতে পারে"
    },
    product_images: ["/images/medicines/methergine-0.2mg.jpg"],
    keywords_bn: ["মেথারজিন", "মিথাইলআর্গোনভিন", "প্রসব পরবর্তী", "রক্তক্ষরণ"]
  }
];

export default gynecologicalDatabase;